### ISSUE TITLE
Create Label to Link Arrow

### ISSUE THREAD

**Issue by mmanoj** [ghostiam/vue-blocks#10]
Dear Team,
Appreciate your advice regarding the below query:

1.Please, advise how we can add labels to the linking arrow between components?
2.How to save the design as XML or JSON structure. So we can load later.

**Comment by ghostiam** [comment]
Hello. Thank you for your interest in the project.

1. There is no such functionality at the moment.
You can do it yourself by editing the "[VueLink.vue](https://github.com/ghostiam/vue-blocks/blob/master/src/components/VueLink.vue)" file and adding text output to the svg generator and calculating the position you need.
You will also need to transfer text, I think it is better to do this in the "[Line](https://github.com/ghostiam/vue-blocks/blob/87fbb4d1dfb32ee5da42c4192a169b00f143eeed/src/components/VueBlocksContainer.vue#L162)" object.
And of course, you will need to store the text somewhere on the scene, so that you can save/load the scene while saving the text (if the text is dynamic).

2. When creating a "VueBlocksContainer" you pass a "scene" object. There it is possible to specify the "sync" modifier for a two-way communication, so the "scene" object will be updated every time it changes and can be saved in any format and loaded in the future (for example, using standard JSON methods).
```
<VueBlocksContainer
...
:scene.sync="scene"
...
/>```

**Comment by mmanoj** [comment]
@ghostiam 

Thanks for the quick reply and support. Really appreciate it. We are studying the code and update you on the progress. Once success we can send you a pull request.
