### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by vivekKodira** [ghostiam/vue-blocks#12]
Hey @ghostiam,

Thank you for the efforts you've put into this repo. I found it very useful in my work.

Are you looking for contributions to this repo? If yes - please add as issues or to the README - I'd like to contribute.

Regards,
Vivek.

**Comment by ghostiam** [comment]
Hi. Thank you for your interest in the project.
To be honest, I abandoned this project because I don't have time for it and unfortunately I like the backend better.

This project was developed by accident and I did not think that anyone would need it...

However, you can fork and improve it however you like! I think I chose a fairly free license for that.

**Comment by vivekKodira** [comment]
Will do. Thanks again.

**Comment by SK0P3iN** [comment]
Hi,
I find this project interesting, and I could really use it for an academic project I am working on. 

Since it is abandoned, do you know of any similar active projects that allow these interactions?

Thanks for your attention!
