### ISSUE TITLE
Add Multiple inputs for the one input slot

### ISSUE THREAD

**Issue by KaumadieKariyawasam** [ghostiam/vue-blocks#16]
Hi, thank you for this great demo, i want to modify your library as i needed requirements.
 I want to add multiple inputs arrow to the one input slot in component.
have any tips to change the library to gets multiple inputs for the one input slot?

**Comment by ghostiam** [comment]
Hello. Thank you for your interest in the project.

Do you want to connect multiple outputs to one input slot?
If so, then you need to modify the functions "linkingStart"(line 325)
https://github.com/ghostiam/vue-blocks/blob/master/src/components/VueBlocksContainer.vue#L325

and "linkingStop"(line 337). 
https://github.com/ghostiam/vue-blocks/blob/master/src/components/VueBlocksContainer.vue#L337

So that the connections do not break off and it is possible to combine multiple into one input slot, remove the filter on lines 339-341
https://github.com/ghostiam/vue-blocks/blob/master/src/components/VueBlocksContainer.vue#L339-L341

**Comment by KaumadieKariyawasam** [comment]
Thank you so much. I was able to do this on your advice
